### ISSUE TITLE
App crash during keyboard is appearing after app active back from background

### ISSUE THREAD

**Issue by laohanme** [RazerMS/rms-mobile-xdk-cocoapods#1]
Produce the crash
During on the steps for FPX payment process and click on any textfield and the keyboard is appearing, then just put the app into background and click back to the app again the crash may happen. But this crash is only happen on real phone device, if i tried on Xcode 12 simulator and reproduce the step above the app is no crash but the keyboard is freeze.

Here the situation below i test using iPhone 12 Pro on simulator
https://user-images.githubusercontent.com/18119268/135122403-c212ba70-1337-4f67-bfe8-73bc6cd4d0f3.mov

**Comment by laohanme** [comment]
Hi @tekjau @hisyamadzha @AfiqRazer sorry for disturb, may i ask if they're any solution for this.

**Comment by wasddsaw** [comment]
hi @laohanme , please try update your xdk version and try testing again

https://cocoapods.org/pods/rms-mobile-xdk-cocoapods
